### PR TITLE
Update `egui` to 0.29

### PR DESCRIPTION
**Pull request by ids1024**
This currently fails to compile:

```
error[E0308]: mismatched types
   --> src/lib.rs:289:58
    |
289 |                     .with_context(|context| Painter::new(context.clone(), "", None))?
    |                                             ------------ ^^^^^^^^^^^^^^^ expected `Rc<Context>`, found `Arc<Context>`
    |                                             |
    |                                             arguments to this function are incorrect
    |
    = note: expected struct `Rc<egui_glow::painter::Context>`
               found struct `Arc<egui_glow::painter::Context
```

https://github.com/emilk/egui/pull/3598 changed this to use `Rc` instead of `Arc`. Smithay's `GlowRenderer::with_context` passes an `&Arc<Context>`. Not sure what can be done other than Smithay using `Rc`, or using a different glow context for egui...

### CODE REVIEW

**Comment by Drakulix** [comment]
I guess we can try to change this to an Rc in smithay and see if something breaks. Theoretically these contexts are thread-safe, as long as they are not current in multiple threads. ~~So I really don't get why egui made this super unnecessary change. Maybe we should open an issue with them.~~ Ah so this is an issue with glow...

Worst case, if both are not an option, would be to create a shared context for egui...

**Comment by Drakulix** [comment]
Seems they have fixed this after the 0.13 release...
https://github.com/grovesNL/glow/commit/edfd08e2a941f4c3db6a3ba6cf84865f7c5365ff

*sigh*

Maybe we can convince egui to change that back, once there is a new glow release. (and then wait for the next egui release? this sucks, maybe we should just temporarily patch this with git dependencies...)

**Comment by Drakulix** [comment]
Looks like egui will fix this in 0.25 again, so lets wait for that I suppose: https://github.com/emilk/egui/pull/3646

**Comment by ids1024** [comment]
Annoying, but it it will eventually be fixed in an update, I suppose.

**Comment by nferhat** [comment]
This is now fixed, but needs update in smithay's glow (update to 0.13) for 0.25 and above

**Comment by Drakulix** [comment]
> This is now fixed, but needs update in smithay's glow (update to 0.13) for 0.25 and above

PRs welcome :)

**Comment by ids1024** [comment]
We can see if things are working properly with the newly released glow 0.14, once https://github.com/emilk/egui/pull/4833 is released.

**Comment by ids1024** [comment]
There's now a new `egui` release, so I've updated this again. It should be ready to merge after https://github.com/Smithay/smithay/pull/1195.

**Comment by Drakulix** [comment]
smithay changes merged.

**Review by Drakulix — APPROVED** [review]

**Pull request merged**
